### ISSUE TITLE
server didn't handle connect and disconnect event

### ISSUE THREAD

**Issue by one0410** [JimmyPun610/MQTTnet.Playground#1]
origin line 63 in Startup.cs:
app.UseMqttServer(server => app.ApplicationServices.GetRequiredService<Mqtt.MqttService>());

should be as following:
app.UseMqttServer(server => app.ApplicationServices.GetRequiredService<Mqtt.MqttService>().ConfigureMqttServer(server));

**Comment by JimmyPun610** [comment]
thanks. I missed that

**Comment by toxicOxygen** [comment]
How do you connect a client(Mqtt Client) to this server ?

**Comment by JimmyPun610** [comment]
> How do you connect a client(Mqtt Client) to this server ?

I think the sample app included client connection from blazer/wpf/xamarin form
